### ISSUE TITLE
Unsupported format character

### ISSUE THREAD

**Issue by ajsb85** [vdrhtc/InLaTeXbot#1]
![screenshot_20170422-212952](https://cloud.githubusercontent.com/assets/663460/25307541/e987f914-27a2-11e7-86ee-7f08f442865a.png)

**Comment by vdrhtc** [comment]
Hello, Alexander!

Thanks for the feedback. You should fix your preamble, it seems to be broken (don't know how this happened as long as the bot checks preambles for compilation errors before registering them). Try changing it back to the default one (below) with /setcustompreamble command.
```
\documentclass{article}
\usepackage[a6paper]{geometry}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{textcomp}
\usepackage{lastpage}
\usepackage{amsmath}
\usepackage{physics}
\usepackage{lipsum}
\pagenumbering{gobble}
```

**Comment by ajsb85** [comment]
It's works! Thank you @vdrhtc
