### ISSUE TITLE
Is the bot online?

### ISSUE THREAD

**Issue by SebastianM-C** [vdrhtc/InLaTeXbot#13]
Hello!
Thanks for writing this!

I added the bot, but it does not appear to work (I don't get any image option when calling it inline). When I try to message it directly (i.e. `/help`), it does not respond.

**Comment by vdrhtc** [comment]
Thank you for notification! Yes indeed it went down, now it's back up, please check again!

**Comment by SebastianM-C** [comment]
Yes, now it works. Thanks!
