### ISSUE TITLE
Telegram Error: file must not be empty

### ISSUE THREAD

**Issue by RickyCow** [vdrhtc/InLaTeXbot#18]
I am getting this error when I use the bot in a chat, both on desktop and on my iPhone.

![image](https://user-images.githubusercontent.com/73363993/117688924-41593a00-b187-11eb-9455-4d80c99cdb57.png)

**Comment by LVotto** [comment]
The same happens here. No solutions as I see.

**Comment by vdrhtc** [comment]
@RickyCow  @LVotto  Thanks for the feedback! It seems to me that I have fixed this problem, please check!

**Comment by LVotto** [comment]
Working like a charm! Thanks, @vdrhtc !
