### ISSUE TITLE
/setcodeincaptionon caption length limit

### ISSUE THREAD

**Issue by sashtkach** [vdrhtc/InLaTeXbot#21]
Telegram used to have a smaller limit for image captions. Then this limit was extended. 
So, basically, the bot cuts off part of the long code even if it fits. 
![20211128_031019.jpg](https://user-images.githubusercontent.com/39911468/143725099-c7abbcb9-da07-458f-a51f-53aedd4bc2ca.jpg)

**Comment by vdrhtc** [comment]
Hello! 
Please check, I have updated the limit. Now it will be 250 chars, corresponding to the limit for the query length.

**Comment by sashtkach** [comment]
> Hello! 
> Please check, I have updated the limit. Now it will be 250 chars, corresponding to the limit for the query length.

Yes, everything is great now. Thank you!
