### ISSUE TITLE
Ability to generate image in bot itself working around inline bots max character count limitation?

### ISSUE THREAD

**Issue by xahon** [vdrhtc/InLaTeXbot#27]
I think it would be a great feature to generate longer images using bot directly (without inline query)
With current limitation it's not even possible to write down a Jacobian matrix expression

**Comment by vdrhtc** [comment]
Hello! Thanks for the feedback. Could you please provide your code? It is possible to use the bot directly (by sending it your query), so maybe I do not understand the question correctly.

**Comment by xahon** [comment]
Oh, really, it works. Sorry for false interruption

**Comment by vdrhtc** [comment]
Ok! No worries!
