### ISSUE TITLE
/setcustompreamble not working (or bad documented)

### ISSUE THREAD

**Issue by JackBluff** [vdrhtc/InLaTeXbot#5]
Hi;
straight to the point.
InLaTexBot conversation:

>/setcustompreamble

>>Great. Let's register a custom preamble for you. Just message me the code, and I'll deal with everything else.

>\documentclass{article}
\usepackage[a6paper]{geometry}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{textcomp}
\usepackage{lastpage}
\usepackage{amsmath}
\usepackage{physics}
\usepackage{lipsum}
\usepackage{mathbb}
\pagenumbering{gobble}
[NOTE: it's the output of /getmypreable + \usepackage{mathbb}]

>>Cool. Let me check it...

>>An empty file with your preamble results in a compilation error. Check your code!

And the new preamble doesn't become the default one.

Is it broken or am I supposed to provide the cone in another way?

**Comment by vdrhtc** [comment]
![default](https://user-images.githubusercontent.com/3819012/45222147-48379c80-b2bc-11e8-9ad8-ef840f073ebd.png)
I've added the error message to the bot's response -- it seems that there's no such package

**Comment by Demonstrandum** [comment]
You need the amsfonts package no? Not mathbb on its own.

**Comment by vdrhtc** [comment]
Yes, indeed
