### ISSUE TITLE
Remove the border

### ISSUE THREAD

**Issue by Gansgar** [vdrhtc/InLaTeXbot#7]
Is it possible to remove the border around the images? It's funny how short request like: "$x^2$" don't have any border, but longer ones like "How does this work?" have a pretty fat border on bottom and top.

**Comment by vdrhtc** [comment]
There was a problem with images of large aspect ration -- they do not fit into the preview window and get clipped. I think this is still the case, so I wouldn't remove the white borders

**Comment by Gansgar** [comment]
Ah okay. Thx
