### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by arandomliz** [vdrhtc/InLaTeXbot#8]
What is your experience: What is the slowest thing in the whole pipeline? E.g. could one provide a faster feedback by maybe MarkDown with MathJax instead?

**Comment by vdrhtc** [comment]
I guess it's the proxy

**Comment by vdrhtc** [comment]
Didn't mean to close yet =)

**Comment by Gansgar** [comment]
What do you mean? 😅

**Comment by vdrhtc** [comment]
> What do you mean? sweat_smile

Since Telegram is blocked in my country, I have to use Tor to connect the bot to the net. However, if I remember correctly, even without the proxy the slowest part was http requests. I think, Webhook API should be used to improve the speed. I'll leave this issue as a reminder.

**Comment by Gansgar** [comment]
Okay. My first thought that the LaTeX rendering would take too long.

**Comment by vdrhtc** [comment]
Not blocked anymore
